version: '3.8'

services:
  app:
    image: resume-app:v01
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:3000"] 
      interval: 30s 
      timeout: 10s 
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:80"] 
      interval: 30s 
      timeout: 10s 
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network

  certbot:
    image: certbot:nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      nginx:
        condition: service_healthy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot --nginx --non-interactive --email replytobishnu@gmail.com --agree-tos --no-eff-email -d bishnupoudel.site && nginx -s reload; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
