version: '3.8'

services:
  app:
    image: resume-app:v01
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot --webroot-path /var/www/certbot --email replytobishnu@gmail.com --agree-tos --no-eff-email -d bishnupoudel.site; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge
