version: '3.8'

services:
  app:
    image: resume-app:v01
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:3000"] 
      interval: 5s 
      timeout: 4s 
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    healthcheck: 
      test: ["CMD", "curl", "http://localhost:3000"] 
      interval: 10s 
      timeout: 20s 
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - letsenc:/etc/letsencrypt
      - certbot:/var/www/certbot

    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network

  certbot:
    image: certbot:nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - letsenc:/etc/letsencrypt
      - certbot:/var/www/certbot
    depends_on:
      nginx:
        condition: service_started
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot -d bishnupoudel.site --email replytobishnu@gmail.com --agree-tos --no-eff-email --non-interactive; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  letsenc:
  certbot:
  nginxpid:
