FROM certbot/certbot:nightly

# Install NGINX and the Certbot NGINX plugin
RUN apk update && \
    apk add --no-cache nginx 

RUN curl -s https://get.acme.sh | sh -s acme.sh

RUN pip install certbot-nginx


