version: "3.9"
services:
  certbot:
    image: nbraun1/certbot:latest
    environment:
      EMAIL: replytobishnu@gmail.com
      DOMAINS: bishnupoudel.site
      RUN_ONCE: 1
    ports:
      - 8080:80
    volumes:
      - ./data/certbot:/etc/letsencrypt
