version: '3.8'

services:  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot --webroot-path /var/www/certbot --email replytobishnu@gmail.com --agree-tos --no-eff-email -d bishnupoudel.site; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge